@Restaurants.API_HostAddress = http://localhost:5000

GET {{Restaurants.API_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{Restaurants.API_HostAddress}}/api/restaurants

###


GET {{Restaurants.API_HostAddress}}/api/restaurants/145

###


DELETE {{Restaurants.API_HostAddress}}/api/restaurants/17

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "Siggis",
  "Description": "A culinary experience like no other",
  "Category": "Turkish",
  "HasDelivery": true,
  "ContactEmail": "info@gourmetdelights.com",
  "ContactNumber": "555-123-4567",
  "City": "Berlin",
  "Street": "Berliner Strasse",
  "PostalCode": "11-111"
}

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/18
Content-Type: application/json

{
  "Name": "Siggis Updated",
  "Description": "This is a sample restaurant description",
  "HasDelivery": false
}

###
