@Restaurants.API_HostAddress = http://localhost:5000

GET {{Restaurants.API_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{Restaurants.API_HostAddress}}/api/restaurants

###


GET {{Restaurants.API_HostAddress}}/api/restaurants/9

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/17

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "Siggis",
  "Description": "A culinary experience like no other",
  "Category": "Turkish",
  "HasDelivery": true,
  "ContactEmail": "info@gourmetdelights.com",
  "ContactNumber": "555-123-4567",
  "City": "Berlin",
  "Street": "Berliner Strasse",
  "PostalCode": "11-111"
}

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/18
Content-Type: application/json

{
  "Name": "Siggis Updated",
  "Description": "This is a sample restaurant description",
  "HasDelivery": false
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurant/9/dishes
Content-Type: application/json

{
  "Name": "Spaghetti Bolognese 2",
  "Description": "Classic Italian pasta",
  "Price": 14.99,
  "KiloCalories": 750
}

###


GET {{Restaurants.API_HostAddress}}/api/restaurant/9/dishes

###

GET {{Restaurants.API_HostAddress}}/api/restaurant/1/dishes/1

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurant/9/dishes

###

GET http://localhost:5000/api/restaurant/9/dishes/7

###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "example@example.com",
  "password": "Example_123"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "example@example.com",
  "password": "Example_123"
}